### ISSUE TITLE
it seems did not work?

### ISSUE THREAD

**Issue by proudlily** [rdebeasi/checked-polyfill#3]
i open the index.html in ie7 ，but  it did not work?did anything that i did wrong?

**Comment by rdebeasi** [comment]
I did test the polyfill in IE7, but it's possible something weird is happening here. Could you send along a screenshot? Are you getting CSS styles as shown on the demo page? Are you getting any console errors? Are you seeing the problem locally only, or also at http://rdebeasi.github.io/checked-polyfill/ ?

Some things to try:
- Make sure IE7 isn't running in compatibility mode.
- If you're extracting the files from a zip, make sure all the files are extracted before opening the page.
- You may need to run the page from a local web server or explicitly allow the page to run JavaScript. Older versions of IE don't allow local pages to run JavaScript by default.

**Comment by proudlily** [comment]
thanks for your word.i download the zip ,and open it on the ie .the ie10,1e9 works,but the ie7 and ie8 didnot work .i make sure that the js and css is contain in the right way . the screenshot did not show any  error.what should i show in the console? sorry for the world that i said

**Comment by rdebeasi** [comment]
Sorry for the delay!

I've double-checked the demo page in IE7, and it seems to work fine. If you open http://rdebeasi.github.io/checked-polyfill/ in IE7, do the checkboxes work correctly?

If you use a local server such as [harp](http://harpjs.com/) to serve your local copy of the files and then use IE7 to open the page from your local server, does that work?

Older versions of IE won't run JavaScript from local files that are opened via file://. JavaScript will only run if the page is loaded from a server using http://.

**Comment by rdebeasi** [comment]
I haven't heard back on this, so I'm going to close the issue for now. Please let me know if you need anything else!

**Comment by proudlily** [comment]
yes,as u said!thx!
