### ISSUE TITLE
Conditionally load file

### ISSUE THREAD

**Issue by gunnx** [rdebeasi/checked-polyfill#4]
Would you recommend that this is loaded via conditional comments?

**Comment by rdebeasi** [comment]
For sure! There are other good ways to load it, but conditional comments will work probably work well for most people.

Other options:
- Detect support for the `:checked` selector, then use a resource loader such as YepNope to load the script. (I'll add AMD support soon.)
- If you're already combining all your scripts into one file, you could include checked polyfill in that file. The polyfill is pretty small, and it exits if it detects native `:checked` support.

The important thing is not to make an extra request for the file in modern browsers.

If you have any other questions, just let me know!
