### ISSUE TITLE
How can i make this code work.

### ISSUE THREAD

**Issue by Ceiron** [rdebeasi/checked-polyfill#6]
Css ----------------------------------------------------------------------

input {
  display: none;
}

label {
  display: inline-block;
  margin: 0 0 -1px;
  padding: 15px 25px;
  font-weight: 600;
  text-align: center;
  color: #bbb;
  border: 1px solid transparent;
}

label:before {
  font-family: fontawesome;
  font-weight: normal;
  margin-right: 10px;
}
/*   f0c0 icon codes font-awesome plugin just saying.  */
label[for*='1']:before {
  content: '\f0c0';
}

label[for*='2']:before {
  content: '\f0e3';
}

label[for*='3']:before {
  content: '\f059';
}

label:hover {
  color: #888;
  cursor: pointer;
}

input:checked + label {
  color: #555;
  border: 1px solid #ddd;
  border-top: 2px solid #3FA5CB;
  border-bottom: 1px solid #fff;
}

#tab1:checked ~ #content1,
#tab2:checked ~ #content2,
#tab3:checked ~ #content3{
  display: block;
}

<main>
  input id="tab1" type="radio" name="tabs" checked>
  <label for="tab1">Hakkımızda</label>
    
  input id="tab2" type="radio" name="tabs">
  label for="tab2">Çalışma Prensibi</label>
    
  input id="tab3" type="radio" name="tabs">
  label for="tab3">Neden biz?</label>
    
    
  section id="content1">
  /section>

  section id="content2">
  /section>
    
  section id="content3">
  /section>

/main>

Yesterday i downloaded mit licenced tab menu plugin , its not working on internet explorer old versions thats why i decided to use your plugin. Thanks by the way :). The problem is im coding noobie there is different codes which i don't know yet. How can i make this css code work with your plugin. Thanks. (i don't know where to add .checked)

**Comment by Ceiron** [comment]
Sorry about that html part is here -----------------------------------------

<main>
  
  <input id="tab1" type="radio" name="tabs" checked>
  <label for="tab1">About us</label>
    
  <input id="tab2" type="radio" name="tabs">
  <label for="tab2">How we work</label>
    
  <input id="tab3" type="radio" name="tabs">
  <label for="tab3">Why us</label>
    
    
  <section id="content1">
    
  </section>

  <section id="content2">
    
  </section>

  <section id="content3">
    
  </section>
    
    
</main>

**Comment by rdebeasi** [comment]
No worries!

Anywhere you use `:checked`, write a second selector with `.checked` instead. For example:

```css
input:checked + label {
color: #555;
border: 1px solid #ddd;
border-top: 2px solid #3FA5CB;
border-bottom: 1px solid #fff;
}

input.checked + label {
color: #555;
border: 1px solid #ddd;
border-top: 2px solid #3FA5CB;
border-bottom: 1px solid #fff;
}
```

This involves duplicating CSS, unfortunately, because IE will ignore CSS blocks that contain selectors that it doesn't recognize.

Does that help?

**Comment by Ceiron** [comment]
As i read plugin is not working on local. So its so difficult to test it. When i use ".checked" tab gets messed up on modern browsers. I decided to make a css file for ie old versions only. I hope it will work.

Thank you so much sir, best regards.
