### ISSUE TITLE
Code is not working #2

### ISSUE THREAD

**Issue by Ceiron** [rdebeasi/checked-polyfill#7]
Hello its me again - https://github.com/rdebeasi/checked-polyfill/issues/6

i tried what you told me but it seems not working. 

http://uguranlar.pe.hu/tarihce.html  (This website im using for test)

How its supposed to work - http://snag.gy/6SyRg.jpg
![unnamed](https://cloud.githubusercontent.com/assets/10236345/10693861/a0927328-79a3-11e5-91b9-e7e6d4051184.png)

This the tab i used 

http://codepen.io/anon/pen/BoYoLr

i tried everything i can , but checked css codes not working on ie old versions. 

Best regards

**Comment by Ceiron** [comment]
No help ?

**Comment by rdebeasi** [comment]
No worries, I haven't forgotten about you! I'll take a closer look and get back to you.

**Comment by rdebeasi** [comment]
I just tried opening the test code, but I get a 403 error. Would you mind making that page accessible? You could also post a demo on CSSPen or JSfilddle, if that's easier. Thanks!

**Comment by Ceiron** [comment]
Im so sorry about that , here you go.

https://jsfiddle.net/h6jsw00m/

http://www.uguranlar.pe.hu/tarihce.html

**Comment by rdebeasi** [comment]
Try calling Checked Polyfill on document ready:

```js
(function($) {          
    $(document).ready(function(){                    
        $('input:radio, input:checkbox').checkedPolyfill();
        $(window).scroll(function(){   
            // etc...
        });
    });
})(jQuery)
```

The script is getting called in the head, outside of a document ready block. When the script runs, most of the page still hasn't been rendered yet, so the script can't access the radio buttons.

Does that help?

**Comment by Ceiron** [comment]
Good news: it doesn't look broken anymore.
Bad news: Tab is not functioning i can't switch between tabs. When i click nothing happens.

http://i.snag.gy/HiJyQ.jpg

Thanks for detailed reply by the way , its good to see people helpful :)

**Comment by rdebeasi** [comment]
You're very welcome! I'll look into this and get back to you.

**Comment by rdebeasi** [comment]
Were you able to sort out the problem? If so, what was the fix?

**Comment by Ceiron** [comment]
i changed the tab im using , 100% works guys :D

**Comment by rdebeasi** [comment]
Awesome, glad to hear it!!!
